// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: interface.proto
#ifndef GRPC_interface_2eproto__INCLUDED
#define GRPC_interface_2eproto__INCLUDED

#include "interface.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace comm {

class ImageService final {
 public:
  static constexpr char const* service_full_name() {
    return "comm.ImageService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status get_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::comm::ImgReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::comm::ImgReply>> Asyncget_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::comm::ImgReply>>(Asyncget_img_by_idxRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::comm::ImgReply>> PrepareAsyncget_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::comm::ImgReply>>(PrepareAsyncget_img_by_idxRaw(context, request, cq));
    }
    virtual ::grpc::Status get_batch(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::comm::BatchReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::comm::BatchReply>> Asyncget_batch(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::comm::BatchReply>>(Asyncget_batchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::comm::BatchReply>> PrepareAsyncget_batch(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::comm::BatchReply>>(PrepareAsyncget_batchRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void get_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest* request, ::comm::ImgReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void get_img_by_idx(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::ImgReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void get_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest* request, ::comm::ImgReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void get_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest* request, ::comm::ImgReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void get_img_by_idx(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::ImgReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void get_img_by_idx(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::ImgReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void get_batch(::grpc::ClientContext* context, const ::comm::BatchRequest* request, ::comm::BatchReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void get_batch(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::BatchReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void get_batch(::grpc::ClientContext* context, const ::comm::BatchRequest* request, ::comm::BatchReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void get_batch(::grpc::ClientContext* context, const ::comm::BatchRequest* request, ::comm::BatchReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void get_batch(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::BatchReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void get_batch(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::BatchReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::comm::ImgReply>* Asyncget_img_by_idxRaw(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::comm::ImgReply>* PrepareAsyncget_img_by_idxRaw(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::comm::BatchReply>* Asyncget_batchRaw(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::comm::BatchReply>* PrepareAsyncget_batchRaw(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status get_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::comm::ImgReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::comm::ImgReply>> Asyncget_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::comm::ImgReply>>(Asyncget_img_by_idxRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::comm::ImgReply>> PrepareAsyncget_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::comm::ImgReply>>(PrepareAsyncget_img_by_idxRaw(context, request, cq));
    }
    ::grpc::Status get_batch(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::comm::BatchReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::comm::BatchReply>> Asyncget_batch(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::comm::BatchReply>>(Asyncget_batchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::comm::BatchReply>> PrepareAsyncget_batch(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::comm::BatchReply>>(PrepareAsyncget_batchRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void get_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest* request, ::comm::ImgReply* response, std::function<void(::grpc::Status)>) override;
      void get_img_by_idx(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::ImgReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void get_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest* request, ::comm::ImgReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void get_img_by_idx(::grpc::ClientContext* context, const ::comm::IdxRequest* request, ::comm::ImgReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void get_img_by_idx(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::ImgReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void get_img_by_idx(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::ImgReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void get_batch(::grpc::ClientContext* context, const ::comm::BatchRequest* request, ::comm::BatchReply* response, std::function<void(::grpc::Status)>) override;
      void get_batch(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::BatchReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void get_batch(::grpc::ClientContext* context, const ::comm::BatchRequest* request, ::comm::BatchReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void get_batch(::grpc::ClientContext* context, const ::comm::BatchRequest* request, ::comm::BatchReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void get_batch(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::BatchReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void get_batch(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::comm::BatchReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::comm::ImgReply>* Asyncget_img_by_idxRaw(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::comm::ImgReply>* PrepareAsyncget_img_by_idxRaw(::grpc::ClientContext* context, const ::comm::IdxRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::comm::BatchReply>* Asyncget_batchRaw(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::comm::BatchReply>* PrepareAsyncget_batchRaw(::grpc::ClientContext* context, const ::comm::BatchRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_get_img_by_idx_;
    const ::grpc::internal::RpcMethod rpcmethod_get_batch_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status get_img_by_idx(::grpc::ServerContext* context, const ::comm::IdxRequest* request, ::comm::ImgReply* response);
    virtual ::grpc::Status get_batch(::grpc::ServerContext* context, const ::comm::BatchRequest* request, ::comm::BatchReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_get_img_by_idx : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_img_by_idx() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_get_img_by_idx() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_img_by_idx(::grpc::ServerContext* /*context*/, const ::comm::IdxRequest* /*request*/, ::comm::ImgReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_img_by_idx(::grpc::ServerContext* context, ::comm::IdxRequest* request, ::grpc::ServerAsyncResponseWriter< ::comm::ImgReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_get_batch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_batch() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_get_batch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_batch(::grpc::ServerContext* /*context*/, const ::comm::BatchRequest* /*request*/, ::comm::BatchReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_batch(::grpc::ServerContext* context, ::comm::BatchRequest* request, ::grpc::ServerAsyncResponseWriter< ::comm::BatchReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_get_img_by_idx<WithAsyncMethod_get_batch<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_get_img_by_idx : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_get_img_by_idx() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::comm::IdxRequest, ::comm::ImgReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::comm::IdxRequest* request, ::comm::ImgReply* response) { return this->get_img_by_idx(context, request, response); }));}
    void SetMessageAllocatorFor_get_img_by_idx(
        ::grpc::experimental::MessageAllocator< ::comm::IdxRequest, ::comm::ImgReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::comm::IdxRequest, ::comm::ImgReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_get_img_by_idx() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_img_by_idx(::grpc::ServerContext* /*context*/, const ::comm::IdxRequest* /*request*/, ::comm::ImgReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_img_by_idx(
      ::grpc::CallbackServerContext* /*context*/, const ::comm::IdxRequest* /*request*/, ::comm::ImgReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_img_by_idx(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::comm::IdxRequest* /*request*/, ::comm::ImgReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_get_batch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_get_batch() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::comm::BatchRequest, ::comm::BatchReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::comm::BatchRequest* request, ::comm::BatchReply* response) { return this->get_batch(context, request, response); }));}
    void SetMessageAllocatorFor_get_batch(
        ::grpc::experimental::MessageAllocator< ::comm::BatchRequest, ::comm::BatchReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::comm::BatchRequest, ::comm::BatchReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_get_batch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_batch(::grpc::ServerContext* /*context*/, const ::comm::BatchRequest* /*request*/, ::comm::BatchReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_batch(
      ::grpc::CallbackServerContext* /*context*/, const ::comm::BatchRequest* /*request*/, ::comm::BatchReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_batch(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::comm::BatchRequest* /*request*/, ::comm::BatchReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_get_img_by_idx<ExperimentalWithCallbackMethod_get_batch<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_get_img_by_idx<ExperimentalWithCallbackMethod_get_batch<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_get_img_by_idx : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_img_by_idx() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_get_img_by_idx() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_img_by_idx(::grpc::ServerContext* /*context*/, const ::comm::IdxRequest* /*request*/, ::comm::ImgReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_get_batch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_batch() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_get_batch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_batch(::grpc::ServerContext* /*context*/, const ::comm::BatchRequest* /*request*/, ::comm::BatchReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_img_by_idx : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_img_by_idx() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_get_img_by_idx() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_img_by_idx(::grpc::ServerContext* /*context*/, const ::comm::IdxRequest* /*request*/, ::comm::ImgReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_img_by_idx(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_batch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_batch() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_get_batch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_batch(::grpc::ServerContext* /*context*/, const ::comm::BatchRequest* /*request*/, ::comm::BatchReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_batch(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_get_img_by_idx : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_get_img_by_idx() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_img_by_idx(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_get_img_by_idx() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_img_by_idx(::grpc::ServerContext* /*context*/, const ::comm::IdxRequest* /*request*/, ::comm::ImgReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_img_by_idx(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_img_by_idx(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_get_batch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_get_batch() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_batch(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_get_batch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_batch(::grpc::ServerContext* /*context*/, const ::comm::BatchRequest* /*request*/, ::comm::BatchReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_batch(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_batch(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_img_by_idx : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_img_by_idx() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::comm::IdxRequest, ::comm::ImgReply>(std::bind(&WithStreamedUnaryMethod_get_img_by_idx<BaseClass>::Streamedget_img_by_idx, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_get_img_by_idx() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_img_by_idx(::grpc::ServerContext* /*context*/, const ::comm::IdxRequest* /*request*/, ::comm::ImgReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_img_by_idx(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::comm::IdxRequest,::comm::ImgReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_batch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_batch() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler< ::comm::BatchRequest, ::comm::BatchReply>(std::bind(&WithStreamedUnaryMethod_get_batch<BaseClass>::Streamedget_batch, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_get_batch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_batch(::grpc::ServerContext* /*context*/, const ::comm::BatchRequest* /*request*/, ::comm::BatchReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_batch(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::comm::BatchRequest,::comm::BatchReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_get_img_by_idx<WithStreamedUnaryMethod_get_batch<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_get_img_by_idx<WithStreamedUnaryMethod_get_batch<Service > > StreamedService;
};

}  // namespace comm


#endif  // GRPC_interface_2eproto__INCLUDED
