# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interface.proto',
  package='comm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0finterface.proto\x12\x04\x63omm\"\x19\n\nIdxRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\"E\n\x08ImgReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05label\x18\x03 \x01(\x05\x12\r\n\x05\x64type\x18\x04 \x01(\t2D\n\x0cImageService\x12\x34\n\x0eget_img_by_idx\x12\x10.comm.IdxRequest\x1a\x0e.comm.ImgReply\"\x00\x62\x06proto3'
)




_IDXREQUEST = _descriptor.Descriptor(
  name='IdxRequest',
  full_name='comm.IdxRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='comm.IdxRequest.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=50,
)


_IMGREPLY = _descriptor.Descriptor(
  name='ImgReply',
  full_name='comm.ImgReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='comm.ImgReply.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='comm.ImgReply.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='comm.ImgReply.label', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='comm.ImgReply.dtype', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['IdxRequest'] = _IDXREQUEST
DESCRIPTOR.message_types_by_name['ImgReply'] = _IMGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdxRequest = _reflection.GeneratedProtocolMessageType('IdxRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDXREQUEST,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:comm.IdxRequest)
  })
_sym_db.RegisterMessage(IdxRequest)

ImgReply = _reflection.GeneratedProtocolMessageType('ImgReply', (_message.Message,), {
  'DESCRIPTOR' : _IMGREPLY,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:comm.ImgReply)
  })
_sym_db.RegisterMessage(ImgReply)



_IMAGESERVICE = _descriptor.ServiceDescriptor(
  name='ImageService',
  full_name='comm.ImageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=123,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_img_by_idx',
    full_name='comm.ImageService.get_img_by_idx',
    index=0,
    containing_service=None,
    input_type=_IDXREQUEST,
    output_type=_IMGREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESERVICE)

DESCRIPTOR.services_by_name['ImageService'] = _IMAGESERVICE

# @@protoc_insertion_point(module_scope)
